{
 "title": "Model Performance & Drift",
 "description": "Monitors the model performance and data drift by RMSE, MAE, R2 scores and the data drift detected status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "R2 Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_r2_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MAE Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_mae_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Drift Detected Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_drift_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RMSE Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_rmse_score", "legendFormat": "__auto" }
   ]
  }
 ]
}